  name: The first workflow
  run-name: ${{ github.actor }} triggered their first workflow! üê£ 
  on: 
    push:
      paths:
        ../simple-workflow

  jobs: 
    the-first-job:
      runs-on: ubuntu-latest
      steps: 
        - run: echo "You thought we would do something better for the first workflow, didn't you?"
        - run: echo "Nahh, Hello World it is!"